version: '3.8'  # Use latest version to ensure compatibility
services:
  app:
    build: .
    stdin_open: true  # Keep STDIN open for interactive input
    tty: true         # Allocate a pseudo-TTY for interaction
    depends_on:       # Ensure the app waits for the DB to start
      - db
    command: java -jar /tmp/seMethods-0.1-alpha-4-jar-with-dependencies.jar
    restart: on-failure  # Optional: restart only if the app crashes

  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
