version: '3'
services:
  app:
    build: .
    stdin_open: true  # Keep STDIN open for the container
    tty: true         # Allocate a pseudo-TTY
    env_file:
      - .env

  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
