name: A workflow for Group 36s App
on: push

jobs:
  build:
    name: World Database Application
    runs-on: ubuntu-20.04
    env:
      CI: True  # Set the CI environment variable globally for the job

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Print environment variables
        run: |
          echo "CI environment variable is: $CI"
          env  # This will print all environment variables

      - name: Unit Tests
        run: mvn -Dtest=napier.com.sem.AppTest test

      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit