name: A workflow for Group 36s App
on: push

jobs:
  build:
    name: World Database Application
    runs-on: ubuntu-20.04
    env: # Define global environment variables
      CI: true  # This sets the CI variable to true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Print environment variables
        run: env
      - name: Unit Tests
        run: mvn -Dtest=napier.com.sem.AppTest test
      - name: Package and Run docker compose
        run: |
          CI: true
          mvn package -DskipTests
          docker compose up --abort-on-container-exit