name: A workflow for Group 36s App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    env: # Define global environment variables
      CI: true  # This sets the CI variable to true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Print environment variables
        run: env  # This will print all environment variables to the log
      - name: Build with Maven
        run: mvn package
      - name: Run docker compose
        run: CI=true docker compose up --abort-on-container-exit
