name: A workflow for Group 36's App
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CI: true  # Set CI environment variable
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'  # Use Java 14
          distribution: 'adopt'
      - name: Print environment variables
        run: env  # Print all environment variables to the log
      - name: Build with Maven
        run: mvn package
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit
